### ISSUE TITLE
For Shinydashboard

### ISSUE THREAD

**Issue by himanshu-sikaria** [treysp/shiny_password#2]
Can you please help in using this in shiny dashboard. Tried using, through an error during the UI part

**Comment by treysp** [comment]
Since the ShinyDashboard layout is so highly structured (with pre-created placeholders like boxes, dropdowns, and info boxes) I don't think it supports the use of only `renderUI()` in `ui.R` (see [here](https://stackoverflow.com/questions/38826893/shinydashboard-does-not-work-with-uioutput)).

You should be able to set up the high-level UI components you need in `ui.R` (e.g., `dashboardHeader()`, `dashboardSidebar()`, and `dashboardBody()`) then put the password login box in one of those containers (body would probably look best). 

If you get it working please submit a pull request. If not, I may have time to work on that in the next couple of weeks.

**Comment by Makoto1021** [comment]
Hi, is this issue already solved? I was following your example but cannot make it work with dashboard. I used `dashboardHeader()``dashboardSidebar()`and `dashboardBody()`but not really helpful. Do you have any solution?
I asked a question on stackoverflow but just wanted to discuss with people here as well. 
https://stackoverflow.com/questions/50512255/r-shiny-building-a-dashboard-with-authentication

**Comment by treysp** [comment]
Incidentally, @skhan8 just opened a pull request #4 demonstrating how to use it in a shinydashboard. See if that works for you!
